name: Py2app Workflow

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: macOS-latest  # Specify the runner environment, in this case, macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: 3.12  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app

      - name: Build application
        run: |
          python setup.py py2app
          ls 

      - name: Upload artifact
        uses: actions/upload-artifact@v2  # Upload the built application as an artifact
        with:
          name: MyApp  # Specify the name of the artifact
          path: dist/  # Specify the path to the built application files
          #chatgpt generated this whole thing lmao
